### ISSUE TITLE
Cache::FastMmap segfaults with files larger than 4GB or so

### ISSUE THREAD

**Issue by toddr** [robmueller/cache-fastmmap#11]
https://rt.cpan.org/Public/Bug/Display.html?id=92518

@autarch opened on Mon Jan 27 16:11:25 2014

```
I'm guessing this is because all the internals are based on 32-bit integers.?
```

**Comment by robmueller** [comment]
Yes. I'd like to update it so everything is 64bit, but just haven't had time to work on it recently.

**Comment by toddr** [comment]
@robmueller thanks for the response. Just didn't want to get this lost in RT. 

In the mean time, I submitted https://github.com/robmueller/cache-fastmmap/pull/12 so people will know where to report issues going forward.

**Comment by robmueller** [comment]
So I was just looking at the code again today, and realised that I didn't need to make everything 64bit, just the file offsets and cache size could be 64bit, while offsets within each page could be 32bit just fine (limiting page sizes to 4G seems fine for now).

So I've just uploaded a new version 1.48 to cpan which does this.
