### ISSUE TITLE
Fails with perls < 5.10

### ISSUE THREAD

**Issue by andk** [robmueller/cache-fastmmap#13]
As per subject. Best illustrated with the matrix:

http://matrix.cpantesters.org/?dist=Cache-FastMmap%201.47

Sample fail report:

http://www.cpantesters.org/cpan/report/eb3e5e1a-3962-11e8-bef7-ef2f924579b0

Diagnostics: 

```
# Global symbol "$serializer" requires explicit package name at /tmpfs/.cpan-build-cpansand/2018040600/Cache-FastMmap-1.47-18/blib/lib/Cache/FastMmap.pm line 598.
```

Offending operator seems to be C<//>

If this cannot easily be fixed, it would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Thanks!

**Comment by robmueller** [comment]
I've just uploaded a new version 1.48 to cpan which should remove the need for // and thus work on perl 5.8 again.
