### ISSUE TITLE
Missing dependency Test::Deep in 1.53

### ISSUE THREAD

**Issue by perlpunk** [robmueller/cache-fastmmap#22]
`t/2.t` is using Test::Deep, but it is not mentioned as a dependency.
I saw this while maintaining the perl modules repo for openSUSE
https://build.opensuse.org/package/show/devel:languages:perl/perl-Cache-FastMmap

**Comment by robmueller** [comment]
Ooops, I wasn't sure where to add this and didn't put it in the right spot. I've uploaded 1.54 which fixed this.
