### ISSUE TITLE
Random test failures (1.53, 1.54)

### ISSUE THREAD

**Issue by eserte** [robmueller/cache-fastmmap#23]
t/2.t fails randomly like this (but sometimes with differing values):
```
#   Failed test 'expire get 12'
#   at t/2.t line 52.
#          got: undef
#     expected: '123'

#   Failed test 'expire get 15'
#   at t/2.t line 56.
#          got: undef
#     expected: '123'

#   Failed test 'expire get 20'
#   at t/2.t line 67.
#          got: undef
#     expected: '123'
# Looks like you failed 3 tests of 51.
t/2.t ... 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/51 subtests 
```
The failures seem to be independent from perl versions or operating systems.

**Comment by robmueller** [comment]
Yeah these tests used sleep()'s to try and check that cache expiry was working as expected. Clearly this is all a bit racy and ugly.

I've now uploaded 1.55 which provides an internal mechanism for overriding Cache::FastMmap's idea of what `time` it is right now and updated the tests to use that, which should make them less flaky and faster.
